import type { CatalogItem } from "./types";

export const PROTOCOL_SHARE = 0.3;
export const CREATOR_SHARE = 0.7;

export const CATALOG: CatalogItem[] = [
  {
    id: "neon-open",
    name: "OPEN neon",
    kind: "furniture",
    price: 9,
    creator: "studio.mira",
    creatorShare: CREATOR_SHARE,
    blurb: "Pink tube sign. Reads from the cafe path. The lot’s first souvenir.",
    glyph: "✦",
    color: "#f472b6",
  },
  {
    id: "war-table",
    name: "War-room table",
    kind: "furniture",
    price: 18,
    creator: "harbor.jules",
    creatorShare: CREATOR_SHARE,
    blurb: "Long oak slab. Fits a C-suite that still likes paper.",
    glyph: "▦",
    color: "#b08960",
  },
  {
    id: "server-rack",
    name: "Quiet rack",
    kind: "furniture",
    price: 22,
    creator: "northwind.rex",
    creatorShare: CREATOR_SHARE,
    blurb: "Two blinking units. Makes the factory feel like it computes.",
    glyph: "▣",
    color: "#64748b",
  },
  {
    id: "bench-gift",
    name: "Plaza bench",
    kind: "furniture",
    price: 6,
    creator: "ember.sage",
    creatorShare: CREATOR_SHARE,
    blurb: "Sit. Watch. The tourism loop starts here.",
    glyph: "☰",
    color: "#a16207",
  },
  {
    id: "planter",
    name: "Night planter",
    kind: "furniture",
    price: 5,
    creator: "lot.ops",
    creatorShare: CREATOR_SHARE,
    blurb: "Deep green bowl. Softens the stone path at dusk.",
    glyph: "❀",
    color: "#4d7c0f",
  },
  {
    id: "glass-tower",
    name: "Glass tower kit",
    kind: "building",
    price: 48,
    creator: "harbor.jules",
    creatorShare: CREATOR_SHARE,
    blurb: "Taller executive box with a roof garden. Cosmetic skin for HQ.",
    glyph: "▲",
    color: "#93c5fd",
  },
  {
    id: "brick-factory",
    name: "Brick factory kit",
    kind: "building",
    price: 42,
    creator: "northwind.rex",
    creatorShare: CREATOR_SHARE,
    blurb: "Sawtooth roof and warm windows. For crews that ship atoms.",
    glyph: "⌂",
    color: "#d6b37a",
  },
  {
    id: "last-light",
    name: "Last Light sky",
    kind: "environment",
    price: 14,
    creator: "studio.mira",
    creatorShare: CREATOR_SHARE,
    blurb: "Dusk grade. The default campus already wears a cousin of this.",
    glyph: "☾",
    color: "#c4a574",
  },
  {
    id: "rain-lot",
    name: "Soft rain",
    kind: "environment",
    price: 12,
    creator: "lumen.kit",
    creatorShare: CREATOR_SHARE,
    blurb: "Fine streaks and darker grass. Good for late work clips.",
    glyph: "☔",
    color: "#7dd3fc",
  },
  {
    id: "founder-hoodie",
    name: "Founder hoodie",
    kind: "outfit",
    price: 8,
    creator: "lot.nova",
    creatorShare: CREATOR_SHARE,
    blurb: "Soft charcoal. The CEO default for a reason.",
    glyph: "hoodie",
    color: "#1e293b",
  },
  {
    id: "chalk-stripe",
    name: "Chalk-stripe",
    kind: "outfit",
    price: 11,
    creator: "harbor.jules",
    creatorShare: CREATOR_SHARE,
    blurb: "CFO armor. Reads as serious from the plaza path.",
    glyph: "suit",
    color: "#334155",
  },
  {
    id: "coveralls",
    name: "Line coveralls",
    kind: "outfit",
    price: 9,
    creator: "northwind.rex",
    creatorShare: CREATOR_SHARE,
    blurb: "Ochre cloth, one pocket for a wrench that is mostly symbolic.",
    glyph: "work",
    color: "#b45309",
  },
  {
    id: "visitor-lanyard",
    name: "Visitor lanyard",
    kind: "outfit",
    price: 4,
    creator: "lumen.kit",
    creatorShare: CREATOR_SHARE,
    blurb: "One stripe. Plaza tourists become part of the picture.",
    glyph: "id",
    color: "#e11d48",
  },
  {
    id: "street-lamp",
    name: "Street lamp",
    kind: "decoration",
    price: 7,
    creator: "lot.ops",
    creatorShare: CREATOR_SHARE,
    blurb: "Warm globe on a thin post. The roads look finished with these.",
    glyph: "⌁",
    color: "#fde68a",
    assetKey: "pack.northshore.lamp.street-lamp",
  },
  {
    id: "cedar-tree",
    name: "City cedar",
    kind: "decoration",
    price: 8,
    creator: "studio.mira",
    creatorShare: CREATOR_SHARE,
    blurb: "A tree you would actually want on your lot.",
    glyph: "▲",
    color: "#2f7a38",
    assetKey: "pack.northshore.tree.cedar",
  },
  {
    id: "hatch-car",
    name: "Hatch",
    kind: "vehicle",
    price: 16,
    creator: "harbor.jules",
    creatorShare: CREATOR_SHARE,
    blurb: "Parked on the grid, tiny against the works.",
    glyph: "▣",
    color: "#c45c4a",
    assetKey: "pack.northshore.car.hatch",
  },
  {
    id: "inn-kit",
    name: "Inn tower kit",
    kind: "building",
    price: 54,
    creator: "ember.sage",
    creatorShare: CREATOR_SHARE,
    blurb: "Stepped hotel silhouette. The docks landmark.",
    glyph: "⌂",
    color: "#e8c4a8",
    assetKey: "pack.northshore.building.hotel.inn",
  },
  {
    id: "forge-kit",
    name: "Forge shed kit",
    kind: "building",
    price: 28,
    creator: "northwind.rex",
    creatorShare: CREATOR_SHARE,
    blurb: "Lean roof, chimney, yard grit.",
    glyph: "⚒",
    color: "#c4a060",
    assetKey: "pack.northshore.building.workshop.workshop",
  },
];

export function catalogById(id: string) {
  return CATALOG.find((item) => item.id === id);
}
