/**
 * Pack GLB URLs keyed by assetId. Publish upserts an existing key; it does not
 * append a second Tesla (or any) entry. Habitat still loads the world GLB.
 */
export const PACK_GLTF = {
  "pack.agentspace.character.agent.civic.01": "/assets/gltf/characters/pack.agentspace.character.agent.civic.01.glb",
  "pack.agentspace.character.pedestrian.casual.01": "/assets/gltf/characters/pack.agentspace.character.pedestrian.casual.01.glb",
  "pack.agentspace.character.pedestrian.worker.01": "/assets/gltf/characters/pack.agentspace.character.pedestrian.worker.01.glb",
  "pack.agentspace.character.npc.human.01": "/assets/gltf/characters/pack.agentspace.character.npc.human.01.glb",
  "pack.agentspace.character.avatar.01": "/assets/gltf/characters/pack.agentspace.character.avatar.01.glb",
  "pack.agentspace.character.avatar.human.01": "/assets/gltf/characters/pack.agentspace.character.avatar.human.01.glb",
  "pack.agentspace.vehicle.car.sedan.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.sedan.01.glb",
  "pack.agentspace.vehicle.car.tesla.sedan.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.tesla.sedan.01.glb?v=98fd414455fabdc7",
  "pack.agentspace.vehicle.car.hatch.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.hatch.01.glb",
  "pack.agentspace.vehicle.car.suv.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.suv.01.glb",
  "pack.agentspace.vehicle.car.taxi.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.taxi.01.glb",
  "pack.agentspace.vehicle.van.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.van.01.glb",
  "pack.agentspace.vehicle.van.delivery.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.van.delivery.01.glb",
  "pack.agentspace.vehicle.bus.city.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.bus.city.01.glb",
  "pack.agentspace.vehicle.truck.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.truck.01.glb",
  "pack.agentspace.vehicle.emergency.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.emergency.01.glb",
  "pack.agentspace.vehicle.bike.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.bike.01.glb",
  "pack.agentspace.streetlight.modern.01": "/assets/gltf/street/pack.agentspace.streetlight.modern.01.glb",
  "pack.agentspace.streetlight.park.01": "/assets/gltf/street/pack.agentspace.streetlight.park.01.glb",
  "pack.agentspace.streetlight.pedestrian.01": "/assets/gltf/street/pack.agentspace.streetlight.pedestrian.01.glb",
  "pack.agentspace.trafficlight.standard.01": "/assets/gltf/street/pack.agentspace.trafficlight.standard.01.glb",
  "pack.agentspace.bench.city.01": "/assets/gltf/street/pack.agentspace.bench.city.01.glb",
  "pack.agentspace.bin.city.01": "/assets/gltf/street/pack.agentspace.bin.city.01.glb",
  "pack.agentspace.bollard.city.01": "/assets/gltf/street/pack.agentspace.bollard.city.01.glb",
  "pack.agentspace.barrier.crowd.01": "/assets/gltf/street/pack.agentspace.barrier.crowd.01.glb",
  "pack.agentspace.busstop.shelter.01": "/assets/gltf/street/pack.agentspace.busstop.shelter.01.glb",
  "pack.agentspace.parking.meter.01": "/assets/gltf/street/pack.agentspace.parking.meter.01.glb",
  "pack.agentspace.sign.post.01": "/assets/gltf/street/pack.agentspace.sign.post.01.glb",
  "pack.agentspace.street.sign.standard.01": "/assets/gltf/street/pack.agentspace.street.sign.standard.01.glb",
  "pack.agentspace.sign.parking.01": "/assets/gltf/street/pack.agentspace.sign.parking.01.glb",
  "pack.agentspace.poster.frame.01": "/assets/gltf/street/pack.agentspace.poster.frame.01.glb",
  "pack.agentspace.billboard.frame.01": "/assets/gltf/street/pack.agentspace.billboard.frame.01.glb",
  "pack.agentspace.clothing.shirt.01": "/assets/gltf/props/pack.agentspace.clothing.shirt.01.glb",
  "pack.agentspace.clothing.jacket.01": "/assets/gltf/props/pack.agentspace.clothing.jacket.01.glb",
  "pack.agentspace.clothing.trousers.01": "/assets/gltf/props/pack.agentspace.clothing.trousers.01.glb",
  "pack.agentspace.clothing.dress.01": "/assets/gltf/props/pack.agentspace.clothing.dress.01.glb",
  "pack.agentspace.clothing.shoes.01": "/assets/gltf/props/pack.agentspace.clothing.shoes.01.glb",
  "pack.agentspace.clothing.hat.01": "/assets/gltf/props/pack.agentspace.clothing.hat.01.glb",
  "pack.agentspace.clothing.accessory.bag.01": "/assets/gltf/props/pack.agentspace.clothing.accessory.bag.01.glb",
  "pack.agentspace.clothing.accessory.hair.01": "/assets/gltf/props/pack.agentspace.clothing.accessory.hair.01.glb",
  "pack.agentspace.clothing.accessory.hair.long.01": "/assets/gltf/props/pack.agentspace.clothing.accessory.hair.long.01.glb",
  "pack.agentspace.clothing.uniform.civic.01": "/assets/gltf/props/pack.agentspace.clothing.uniform.civic.01.glb",
  "pack.agentspace.hydrant.city.01": "/assets/gltf/street/pack.agentspace.hydrant.city.01.glb",
  "pack.agentspace.gutter.strip.01": "/assets/gltf/environment/pack.agentspace.gutter.strip.01.glb",
  "pack.agentspace.building.echt.01": "/assets/gltf/buildings/pack.agentspace.building.echt.01.glb?v=4599525ecdd4a9ee",
  "pack.agentspace.building.echt.02": "/assets/gltf/buildings/pack.agentspace.building.echt.02.glb?v=f3a0bd4efef3c807",
  "pack.agentspace.building.nova.01": "/assets/gltf/buildings/pack.agentspace.building.nova.01.glb?v=d1fa16c7fccc3a78",
  "pack.agentspace.building.corner.01": "/assets/gltf/buildings/pack.agentspace.building.corner.01.glb?v=b057632fc7da259b",
  "pack.agentspace.building.loft.01": "/assets/gltf/buildings/pack.agentspace.building.loft.01.glb?v=1f1230f1facb6d2b",
  "pack.agentspace.building.land-campus-1.01": "/assets/gltf/buildings/pack.agentspace.building.land-campus-1.01.glb?v=438a017c39e394c3",
  "pack.agentspace.building.gallery.spark.01": "/assets/gltf/buildings/pack.agentspace.building.gallery.spark.01.glb?v=bbd9a0bfdf089010",
  "pack.agentspace.building.gallery.nova.01": "/assets/gltf/buildings/pack.agentspace.building.gallery.nova.01.glb?v=18412f3c7ddbdd31",
  "pack.agentspace.building.gallery.loft.01": "/assets/gltf/buildings/pack.agentspace.building.gallery.loft.01.glb?v=4ada551e35bef4a9",
  "pack.agentspace.building.gallery.orbit.01": "/assets/gltf/buildings/pack.agentspace.building.gallery.orbit.01.glb?v=80b7a42a2a0c84cf",
  "pack.agentspace.building.gallery.corner.01": "/assets/gltf/buildings/pack.agentspace.building.gallery.corner.01.glb?v=bf3fa640e8cb061c",
  "pack.agentspace.building.gallery.forge.01": "/assets/gltf/buildings/pack.agentspace.building.gallery.forge.01.glb?v=90e5e5693c32c9b5",
} as const;

export type PackAssetId = keyof typeof PACK_GLTF;
