/**
 * Pack GLB URLs keyed by assetId. Publish upserts an existing key; it does not
 * append a second Tesla (or any) entry. Habitat still loads the world GLB.
 */
export const PACK_GLTF = {
  "pack.agentspace.character.agent.civic.01": "/assets/gltf/characters/pack.agentspace.character.agent.civic.01.glb",
  "pack.agentspace.character.pedestrian.casual.01": "/assets/gltf/characters/pack.agentspace.character.pedestrian.casual.01.glb",
  "pack.agentspace.character.pedestrian.worker.01": "/assets/gltf/characters/pack.agentspace.character.pedestrian.worker.01.glb",
  "pack.agentspace.character.npc.human.01": "/assets/gltf/characters/pack.agentspace.character.npc.human.01.glb",
  "pack.agentspace.character.avatar.01": "/assets/gltf/characters/pack.agentspace.character.avatar.01.glb",
  "pack.agentspace.character.avatar.human.01": "/assets/gltf/characters/pack.agentspace.character.avatar.human.01.glb",
  "pack.agentspace.vehicle.car.sedan.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.sedan.01.glb",
  "pack.agentspace.vehicle.car.tesla.sedan.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.tesla.sedan.01.glb?v=98fd414455fabdc7",
  "pack.agentspace.vehicle.car.hatch.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.hatch.01.glb",
  "pack.agentspace.vehicle.car.suv.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.suv.01.glb",
  "pack.agentspace.vehicle.car.taxi.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.car.taxi.01.glb",
  "pack.agentspace.vehicle.van.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.van.01.glb",
  "pack.agentspace.vehicle.van.delivery.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.van.delivery.01.glb",
  "pack.agentspace.vehicle.bus.city.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.bus.city.01.glb",
  "pack.agentspace.vehicle.truck.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.truck.01.glb",
  "pack.agentspace.vehicle.emergency.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.emergency.01.glb",
  "pack.agentspace.vehicle.bike.01": "/assets/gltf/vehicles/pack.agentspace.vehicle.bike.01.glb",
  "pack.agentspace.streetlight.modern.01": "/assets/gltf/street/pack.agentspace.streetlight.modern.01.glb",
  "pack.agentspace.streetlight.park.01": "/assets/gltf/street/pack.agentspace.streetlight.park.01.glb",
  "pack.agentspace.streetlight.pedestrian.01": "/assets/gltf/street/pack.agentspace.streetlight.pedestrian.01.glb",
  "pack.agentspace.trafficlight.standard.01": "/assets/gltf/street/pack.agentspace.trafficlight.standard.01.glb",
  "pack.agentspace.bench.city.01": "/assets/gltf/street/pack.agentspace.bench.city.01.glb",
  "pack.agentspace.bin.city.01": "/assets/gltf/street/pack.agentspace.bin.city.01.glb",
  "pack.agentspace.bollard.city.01": "/assets/gltf/street/pack.agentspace.bollard.city.01.glb",
  "pack.agentspace.barrier.crowd.01": "/assets/gltf/street/pack.agentspace.barrier.crowd.01.glb",
  "pack.agentspace.busstop.shelter.01": "/assets/gltf/street/pack.agentspace.busstop.shelter.01.glb",
  "pack.agentspace.parking.meter.01": "/assets/gltf/street/pack.agentspace.parking.meter.01.glb",
  "pack.agentspace.sign.post.01": "/assets/gltf/street/pack.agentspace.sign.post.01.glb",
  "pack.agentspace.street.sign.standard.01": "/assets/gltf/street/pack.agentspace.street.sign.standard.01.glb",
  "pack.agentspace.sign.parking.01": "/assets/gltf/street/pack.agentspace.sign.parking.01.glb",
  "pack.agentspace.poster.frame.01": "/assets/gltf/street/pack.agentspace.poster.frame.01.glb",
  "pack.agentspace.billboard.frame.01": "/assets/gltf/street/pack.agentspace.billboard.frame.01.glb",
  "pack.agentspace.clothing.shirt.01": "/assets/gltf/props/pack.agentspace.clothing.shirt.01.glb",
  "pack.agentspace.clothing.jacket.01": "/assets/gltf/props/pack.agentspace.clothing.jacket.01.glb",
  "pack.agentspace.clothing.trousers.01": "/assets/gltf/props/pack.agentspace.clothing.trousers.01.glb",
  "pack.agentspace.clothing.dress.01": "/assets/gltf/props/pack.agentspace.clothing.dress.01.glb",
  "pack.agentspace.clothing.shoes.01": "/assets/gltf/props/pack.agentspace.clothing.shoes.01.glb",
  "pack.agentspace.clothing.hat.01": "/assets/gltf/props/pack.agentspace.clothing.hat.01.glb",
  "pack.agentspace.clothing.accessory.bag.01": "/assets/gltf/props/pack.agentspace.clothing.accessory.bag.01.glb",
  "pack.agentspace.clothing.accessory.hair.01": "/assets/gltf/props/pack.agentspace.clothing.accessory.hair.01.glb",
  "pack.agentspace.clothing.accessory.hair.long.01": "/assets/gltf/props/pack.agentspace.clothing.accessory.hair.long.01.glb",
  "pack.agentspace.clothing.uniform.civic.01": "/assets/gltf/props/pack.agentspace.clothing.uniform.civic.01.glb",
  "pack.agentspace.hydrant.city.01": "/assets/gltf/street/pack.agentspace.hydrant.city.01.glb",
  "pack.agentspace.gutter.strip.01": "/assets/gltf/environment/pack.agentspace.gutter.strip.01.glb",
  "pack.agentspace.building.echt.01": "/assets/gltf/buildings/pack.agentspace.building.echt.01.glb?v=4599525ecdd4a9ee",
  "pack.agentspace.building.echt.02": "/assets/gltf/buildings/pack.agentspace.building.echt.02.glb?v=5a65aa054ce4baa2",
} as const;

export type PackAssetId = keyof typeof PACK_GLTF;
